//package testesDeCodigosJava;
//PACKAGE TESTEDOISPROJETOX;
//
//IMPORT JAVA.UTIL.REGEX.PATTERN;
//IMPORT JAVA.UTIL.CONCURRENT.TIMEUNIT;
//IMPORT ORG.JUNIT.*;
//IMPORT STATIC ORG.JUNIT.ASSERT.*;
//IMPORT STATIC ORG.HAMCREST.COREMATCHERS.*;
//IMPORT ORG.OPENQA.SELENIUM.*;
//IMPORT ORG.OPENQA.SELENIUM.FIREFOX.FIREFOXDRIVER;
//IMPORT ORG.OPENQA.SELENIUM.SUPPORT.UI.SELECT;
//IMPORT JAVA.*;
//IMPORT JAVA.IO.FILEWRITER;
//IMPORT JAVA.IO.IOEXCEPTION;
//IMPORT JAVA.IO.PRINTWRITER;
//
//PUBLIC CLASS MAIN {
//
//	PUBLIC STATIC VOID MAIN(STRING[] ARGS) THROWS IOEXCEPTION {
//
//		WEBDRIVER DRIVER = NEW FIREFOXDRIVER();
//
//		INT I; 
//
//		DRIVER.GET("HTTP://WWW.FILFILTER.COM.TR/EN/OC-MUADIL-URUN-REF.PHP");
//
//		FOR( I=1 ; I<10 ; I++ ){
//
//			DRIVER.FINDELEMENT(BY.LINKTEXT("PRODUCTS")).CLICK();
//
//			NEW SELECT(DRIVER.FINDELEMENT(BY.ID("FILTRE-SELECT"))).SELECTBYVISIBLETEXT("OIL FILTER");
//
//			DRIVER.FINDELEMENT(BY.CSSSELECTOR("INPUT.BUTTON")).CLICK();
//
//			//		DRIVER.MANAGE().TIMEOUTS().IMPLICITLYWAIT(30 , TIMEUNIT.SECONDS);
//
//			DRIVER.FINDELEMENT(BY.XPATH("//DIV[@ID='FILTRE-SONUC']/A["  + I + "]/DIV")).CLICK();
//
//			DRIVER.MANAGE().TIMEOUTS().IMPLICITLYWAIT(30 , TIMEUNIT.SECONDS);
//
//			STRING OD = DRIVER.FINDELEMENT(BY.ID("COL4")).GETTEXT();
//			
//			STRING[] VET = OD.SPLIT(" ");
//
//			//			SYSTEM.OUT.PRINTLN(OD);
//
//
//			//			FOR( I=1 ; I<10 ; I++ ){
//			//
//			//				STRING OD = DRIVER.FINDELEMENT(BY.ID("COL4")).GETTEXT();
//			//
//			//				SYSTEM.OUT.PRINTLN(OD);
//			//			}
//
//			FILEWRITER ARQUIVO = NEW FILEWRITER("C:\\USERS\\JOSE.RODRIGUES\\DOCUMENTS\\TESTE\\ORDILEI PROJETO DE BUSCAS FILTROS DE OLEO\\LINK 4\\"+I+".TXT");
//			PRINTWRITER GRAVARARQ = NEW PRINTWRITER(ARQUIVO);
//
//			INT J=0;
//
//			GRAVARARQ.PRINTF("+--FILTROS--+%N");
//			
////			FOR(; J<VET.LENGTH; J++){
////			GRAVARARQ.PRINTF("| %S  % S|%N", VET[J] , VET[J+1] );
////			}
////		
////			GRAVARARQ.PRINTF("| %S |%N", VET [I] );
//			
//			GRAVARARQ.PRINTF("| %S |%N", OD );
//			
//			GRAVARARQ.PRINTF("+-------------+%N");
//
//			ARQUIVO.CLOSE();
//
//		}
//
//	}
//
//
//}
//



